language: cpp
compiler: clang
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - ninja-build
      - xorg-dev
script:
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - cmake --build .
