language: cpp
compiler: clang
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - ninja-build
      - xorg-dev
script:
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - cmake --build .
  - ./tests/allTests
