skip_tags: true
before_build:
  - git submodule update --init
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - .\tests\Debug\allTests.exe
artifacts:
  - path: \build\Debug\app.exe
    name: app
