skip_tags: true
install:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan --version
before_build:
  - git submodule update --init
build_script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - .\bin\allTests.exe
artifacts:
  - path: \build\bin\app.exe
    name: app
